{% set name = "gTTS" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pndurette/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 92bc99e25f24970a22132cda59a891c8a769bed28cccf2b2535ced1a6bacdb68

build:
  number: 0
  noarch: python
  entry_points:
    - gtts-cli = gtts.cli:tts_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - click >=7.1,<8.2
    - requests >=2.27,<3

test:
  source_files:
    - gtts/tests
  imports:
    - gtts
    - gtts.tests
  commands:
    - pip check
    - gtts-cli --help
    - pytest -vvv --capture=tee-sys -k "not file_ascii and not file_utf8" gtts/tests
  requires:
    - mock
    - pip
    - pytest
    - testfixtures

about:
  home: https://github.com/pndurette/gTTS
  doc_url: http://gtts.readthedocs.org/
  summary: Python library and CLI tool to interface with Google Translate text-to-speech API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
