{% set name = "gTTS" %}
{% set version = "2.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pndurette/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eb80495db5b1e0537ca8d74a58b8be2c72ab28e3a245856d532b651339d11446

build:
  number: 0
  noarch: python
  entry_points:
    - gtts-cli = gtts.cli:tts_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61
  run:
    - python >=3.7
    - click >=7.1,<8.2
    - requests >=2.27,<3

test:
  source_files:
    - gtts/tests
  imports:
    - gtts
    - gtts.tests
  commands:
    - pip check
    - gtts-cli --help
    - pytest -vvv --capture=tee-sys -k "not file_ascii and not file_utf8 and not test_all" gtts/tests
  requires:
    - pip
    - pytest >= 7.1.3,< 8.4.0
    - testfixtures

about:
  home: https://github.com/pndurette/gTTS
  doc_url: http://gtts.readthedocs.org/
  summary: Python library and CLI tool to interface with Google Translate text-to-speech API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
